theme: jekyll-theme-minimal
title: "2010 Mazda 3 - For Sale"
description: "This 2010 Mazda 3 2.5 S is in excellent condition, with 195K miles and no mechanical issues. Asking price: $5000."
baseurl: "/mazda3-for-sale"