theme: jekyll-theme-minimal
title: "2010 Mazda 3 - A Premium Driving Experience"
description: "Excellent condition 2010 Mazda 3 2.5 S, 195K miles, no mechanical issues. Price reduced to $5,600!"
baseurl: "/mazda3-for-sale"